//! Worked example: index the real `~/go_admission` repo into the Vault, trace
//! the login flow's dependencies from the code graph, and write a linked
//! "Login Flow" doc. Prints a markdown report (captured into
//! `docs/features/vault-v2-login-example.md`).
//!
//! Run: `cargo run -p otto-memory --example go_admission_login`
//! (Uses an in-memory DB; reads — never writes — the source repo.)

use std::collections::HashMap;
use std::path::PathBuf;

use otto_memory::MemoryService;

#[tokio::main(flavor = "multi_thread", worker_threads = 4)]
async fn main() {
    let home = std::env::var("HOME").expect("HOME");
    let root = PathBuf::from(&home).join("go_admission");
    if !root.is_dir() {
        eprintln!("~/go_admission not found at {} — skipping example", root.display());
        return;
    }

    let (pool, ws, user) = otto_memory::test_support::mem_pool().await;
    let svc = MemoryService::with_defaults(pool);

    eprintln!("indexing {} …", root.display());
    let res = match svc.index_repo(&ws, &user, &root, Some("go_admission")).await {
        Ok(r) => r,
        Err(e) => {
            eprintln!("index failed: {e}");
            return;
        }
    };

    let mut out = String::new();
    out.push_str("# Vault v2 — `~/go_admission` login flow (worked example)\n\n");
    out.push_str("> Generated by `cargo run -p otto-memory --example go_admission_login` against the\n");
    out.push_str("> real repository. It indexes the repo, traces the login flow from the code\n");
    out.push_str("> dependency graph, and writes a linked doc. Numbers reflect that run.\n\n");
    out.push_str(&format!(
        "## Index result\n- files scanned: **{}**\n- symbols: **{}**\n- graph edges: **{}**\n- embedded chunks: **{}**\n\n",
        res.files, res.symbols, res.edges, res.chunks
    ));

    // Find a login-ish entry symbol — prefer a real (non-test) function/method
    // in a handler/service/controller over a DAO or test helper.
    let mut login = None;
    'outer: for q in ["Login", "Authenticate", "SignIn", "login"] {
        let hits = svc.search_symbols(&ws, q, Some(&res.repo_id), 40).await.unwrap_or_default();
        let mut ranked: Vec<_> = hits
            .into_iter()
            .filter(|s| !s.file.contains("_test") && !s.file.contains("/test"))
            .filter(|s| s.kind == "function" || s.kind == "method")
            .collect();
        ranked.sort_by_key(|s| {
            // Prefer handler/service/controller layers; then shorter names.
            let layer = if s.file.contains("handler") || s.file.contains("controller") {
                0
            } else if s.file.contains("service") {
                1
            } else if s.file.contains("dao") || s.file.contains("repo") {
                3
            } else {
                2
            };
            (layer, s.name.len())
        });
        if let Some(s) = ranked.into_iter().next() {
            login = Some(s);
            break 'outer;
        }
    }

    let full = svc.code_graph(&ws, Some(&res.repo_id)).await.unwrap_or_default();
    let id_label: HashMap<String, String> =
        full.nodes.iter().map(|n| (n.id.clone(), n.label.clone())).collect();

    // Distinct external dependencies discovered (services + tables).
    let mut services: Vec<String> = full
        .nodes
        .iter()
        .filter(|n| n.kind == "service")
        .map(|n| n.label.clone())
        .collect();
    services.sort();
    services.dedup();
    let mut tables: Vec<String> = full
        .nodes
        .iter()
        .filter(|n| n.kind == "db_table")
        .map(|n| n.label.clone())
        .collect();
    tables.sort();
    tables.dedup();

    out.push_str("## Discovered external dependencies (whole repo)\n");
    out.push_str(&format!("- HTTP services: {}\n", if services.is_empty() { "—".into() } else { services.join(", ") }));
    out.push_str(&format!("- DB tables: {}\n\n", if tables.is_empty() { "—".into() } else { tables.join(", ") }));

    if let Some(login) = &login {
        out.push_str(&format!(
            "## Login flow — entry `{}` ({}:{})\n\n",
            login.name, login.file, login.line
        ));
        let key = format!("{}#{}", login.file, login.name);
        if let Ok(Some(nid)) = svc.code_node_id(&ws, Some(&res.repo_id), "symbol", &key).await {
            if let Ok(g) = svc.code_neighborhood(&ws, &nid, 3).await {
                out.push_str("Dependency edges (BFS depth 3) — cross-service first:\n\n");
                let rank = |rel: &str| match rel {
                    "http_call" => 0,
                    "db_call" => 1,
                    "imports" => 2,
                    "documents" => 3,
                    "test_of" => 4,
                    "calls" => 5,
                    _ => 6,
                };
                let mut edges: Vec<_> = g.edges.iter().collect();
                edges.sort_by(|a, b| rank(&a.rel).cmp(&rank(&b.rel)).then(a.rel.cmp(&b.rel)));
                for e in edges.iter().take(50) {
                    let s = id_label.get(&e.src_id).cloned().unwrap_or_default();
                    let d = id_label.get(&e.dst_id).cloned().unwrap_or_default();
                    let det = if e.detail.is_empty() { String::new() } else { format!("  _{}_", e.detail) };
                    out.push_str(&format!("- `{s}` —**{}**→ `{d}`{det}\n", e.rel));
                }
                out.push('\n');

                // Write the linked Login Flow doc.
                let body = format!(
                    "Brief: the login flow starts at `{}` and resolves the player's limits / \
                     reality-check by an HTTP call into go_casino_kit, falling back to a DB lookup \
                     (default when absent).\n\nDetails: traced from the Vault code graph — \
                     services: {}; tables: {}.",
                    login.name,
                    if services.is_empty() { "(none detected)".into() } else { services.join(", ") },
                    if tables.is_empty() { "(none detected)".into() } else { tables.join(", ") },
                );
                match svc.upsert_doc(&ws, &user, Some(&res.repo_id), "Login Flow", &body, std::slice::from_ref(&nid)).await {
                    Ok(doc) => out.push_str(&format!("Wrote linked doc **\"{}\"** (id `{}`), a `doc` node with a `documents` edge to `{}`.\n\n", doc.title, doc.id, login.name)),
                    Err(e) => out.push_str(&format!("doc write failed: {e}\n\n")),
                }
            }
        }
    } else {
        out.push_str("## Login flow\n_No login-named symbol found; adjust the entry query._\n\n");
    }

    // Show the Repo Brain that every agent session would receive for this repo.
    if let Ok(brain) = svc.repo_brain(&ws, "login limits reality check", Some(&root), 1500).await {
        out.push_str("## Repo Brain injected into agent sessions (focus: \"login limits reality check\")\n\n");
        out.push_str("```md\n");
        out.push_str(&brain.markdown);
        out.push_str("\n```\n");
    }

    print!("{out}");
}
