//! Runtime-plugins registry (migration 0062).
//!
//! Stores installed out-of-process plugins. The supervisor reads `list_enabled`
//! at boot/refresh to spawn sidecars; the reverse proxy + management API read/write
//! here; the host API authenticates a sidecar via [`PluginsRepo::find_enabled_by_token`].

use chrono::Utc;
use serde::Serialize;
use sqlx::{Row, SqlitePool};

use otto_core::{Error, Result};

/// An installed runtime plugin. `token` is never serialized to clients.
#[derive(Debug, Clone, Serialize)]
pub struct PluginRecord {
    pub slug: String,
    pub name: String,
    pub icon: String,
    pub version: String,
    pub description: String,
    pub source: String,
    pub exec: Vec<String>,
    pub ui_dir: Option<String>,
    pub health: String,
    pub enabled: bool,
    #[serde(skip_serializing)]
    pub token: String,
    pub installed_at: String,
}

/// Fields needed to install/replace a plugin (token generated by the caller).
pub struct NewPlugin {
    pub slug: String,
    pub name: String,
    pub icon: String,
    pub version: String,
    pub description: String,
    pub source: String,
    pub exec: Vec<String>,
    pub ui_dir: Option<String>,
    pub health: String,
    pub token: String,
}

#[derive(Clone)]
pub struct PluginsRepo {
    pool: SqlitePool,
}

fn row_to_record(r: &sqlx::sqlite::SqliteRow) -> Result<PluginRecord> {
    let exec_json: String = r.get("exec_json");
    let exec: Vec<String> = serde_json::from_str(&exec_json)
        .map_err(|e| Error::Internal(format!("plugin exec_json parse: {e}")))?;
    Ok(PluginRecord {
        slug: r.get("slug"),
        name: r.get("name"),
        icon: r.get("icon"),
        version: r.get("version"),
        description: r.get("description"),
        source: r.get("source"),
        exec,
        ui_dir: r.get("ui_dir"),
        health: r.get("health"),
        enabled: r.get::<i64, _>("enabled") != 0,
        token: r.get("token"),
        installed_at: r.get("installed_at"),
    })
}

const COLS: &str =
    "slug, name, icon, version, description, source, exec_json, ui_dir, health, enabled, token, installed_at";

impl PluginsRepo {
    pub fn new(pool: SqlitePool) -> Self {
        Self { pool }
    }

    /// Install or replace a plugin (preserves nothing; enabled defaults to off).
    pub async fn upsert(&self, p: NewPlugin) -> Result<PluginRecord> {
        let exec_json = serde_json::to_string(&p.exec)
            .map_err(|e| Error::Internal(format!("plugin exec encode: {e}")))?;
        let now = Utc::now().to_rfc3339();
        sqlx::query(
            "INSERT INTO plugins (slug, name, icon, version, description, source, exec_json, ui_dir, health, enabled, token, installed_at)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 0, ?, ?)
             ON CONFLICT(slug) DO UPDATE SET
               name=excluded.name, icon=excluded.icon, version=excluded.version,
               description=excluded.description, source=excluded.source, exec_json=excluded.exec_json,
               ui_dir=excluded.ui_dir, health=excluded.health, token=excluded.token",
        )
        .bind(&p.slug).bind(&p.name).bind(&p.icon).bind(&p.version).bind(&p.description)
        .bind(&p.source).bind(&exec_json).bind(&p.ui_dir).bind(&p.health).bind(&p.token).bind(&now)
        .execute(&self.pool)
        .await
        .map_err(|e| Error::Internal(format!("plugin upsert: {e}")))?;
        self.get(&p.slug)
            .await?
            .ok_or_else(|| Error::Internal("plugin vanished after upsert".into()))
    }

    pub async fn get(&self, slug: &str) -> Result<Option<PluginRecord>> {
        let row = sqlx::query(&format!("SELECT {COLS} FROM plugins WHERE slug = ?"))
            .bind(slug)
            .fetch_optional(&self.pool)
            .await
            .map_err(|e| Error::Internal(format!("plugin get: {e}")))?;
        row.as_ref().map(row_to_record).transpose()
    }

    pub async fn list(&self) -> Result<Vec<PluginRecord>> {
        let rows = sqlx::query(&format!("SELECT {COLS} FROM plugins ORDER BY name"))
            .fetch_all(&self.pool)
            .await
            .map_err(|e| Error::Internal(format!("plugin list: {e}")))?;
        rows.iter().map(row_to_record).collect()
    }

    pub async fn list_enabled(&self) -> Result<Vec<PluginRecord>> {
        Ok(self.list().await?.into_iter().filter(|p| p.enabled).collect())
    }

    /// Installed slugs (for the capabilities map).
    pub async fn list_slugs(&self) -> Result<Vec<String>> {
        let rows = sqlx::query("SELECT slug FROM plugins ORDER BY slug")
            .fetch_all(&self.pool)
            .await
            .map_err(|e| Error::Internal(format!("plugin slugs: {e}")))?;
        Ok(rows.iter().map(|r| r.get::<String, _>("slug")).collect())
    }

    pub async fn set_enabled(&self, slug: &str, enabled: bool) -> Result<()> {
        sqlx::query("UPDATE plugins SET enabled = ? WHERE slug = ?")
            .bind(enabled as i64)
            .bind(slug)
            .execute(&self.pool)
            .await
            .map_err(|e| Error::Internal(format!("plugin set_enabled: {e}")))?;
        Ok(())
    }

    pub async fn delete(&self, slug: &str) -> Result<()> {
        sqlx::query("DELETE FROM plugins WHERE slug = ?")
            .bind(slug)
            .execute(&self.pool)
            .await
            .map_err(|e| Error::Internal(format!("plugin delete: {e}")))?;
        Ok(())
    }

    /// Resolve an enabled plugin by its host-API token (sidecar authentication).
    pub async fn find_enabled_by_token(&self, token: &str) -> Result<Option<PluginRecord>> {
        let row = sqlx::query(&format!(
            "SELECT {COLS} FROM plugins WHERE token = ? AND enabled = 1"
        ))
        .bind(token)
        .fetch_optional(&self.pool)
        .await
        .map_err(|e| Error::Internal(format!("plugin by token: {e}")))?;
        row.as_ref().map(row_to_record).transpose()
    }
}
