<script lang="ts" module>
  // Builder state survives unmount (tab switch, "Open in editor") and
  // connection flips: each connection gets its own snapshot here, restored
  // when the builder remounts or the user switches back. Module-level on
  // purpose — the component is mounted under `{#if mainTab === 'builder'}`.
  import type { CardTable as CacheCard, CanvasEdge as CacheEdge, Clauses as CacheClauses } from './builder/canvas-model';
  interface BuilderSnapshot {
    tables: CacheCard[];
    edges: CacheEdge[];
    clauses: CacheClauses;
    selectedDb: string;
    canvasH: number | null;
  }
  const builderCache = new Map<string, BuilderSnapshot>();
</script>

<script lang="ts">
  // Visual query builder for the SQL engines (MySQL · PostgreSQL · ClickHouse).
  //
  //  ┌ tables ┐┌──────────── canvas: table cards + drawn JOINs ─────────────┐
  //  │ search ││ drag a column onto another to join; FK suggestions below    │
  //  │ list   │├── clauses ─────────────────────────────┬── SQL (live) ──────┤
  //  │        ││ Columns · Filters · Group by · Having   │ issues · preview   │
  //  │        ││ Sort · Limit                            │ Open in editor/Run │
  //  └────────┘└─────────────────────────────────────────┴────────────────────┘
  //
  // The canvas owns FROM/JOIN; the clause panel owns everything else. The SQL
  // is generated by builder/sql-builder.ts (dialect quoting, escaped values),
  // never by string-pasting here. "Open in Builder" on a query tab parses a
  // SELECT back into this model (round trip).
  import { auth } from '../../lib/stores/auth.svelte';
  import { databaseAccessChild } from '../../lib/access-options';
  import { resourceAccess } from '../../lib/stores/resource-access.svelte';
  import Icon from '../../lib/components/Icon.svelte';
  import EmptyState from '../../lib/components/EmptyState.svelte';
  import { ctxMenu } from '../../lib/contextmenu.svelte';
  import { toasts } from '../../lib/toast.svelte';
  import { database } from '../../lib/stores/database.svelte';
  import type { ObjectDetail } from '../../lib/api/types';
  import {
    OPS,
    aggregatesFor,
    buildSelect,
    defaultAggAlias,
    emptyGroup,
    nid,
    opsFor,
    parseSelect,
    splitList,
    suggestGroupBy,
    validate,
    valueKind,
    type AggFn,
    type ColRef,
    type CondGroup,
    type Condition,
    type Dialect,
    type JoinType,
    type Op,
    type OrderItem,
    type SelectItem,
  } from './builder/sql-builder';
  import {
    dropAlias,
    fkSuggestions,
    renameAlias,
    toQuery,
    uniqueAlias,
    walkCanvas,
    type CanvasEdge,
    type CardTable,
    type Clauses,
  } from './builder/canvas-model';

  const JOIN_TYPES: JoinType[] = ['INNER', 'LEFT', 'RIGHT', 'FULL'];

  // ── Card geometry (constants → anchor math is exact, no measurement) ───────
  const CARD_W = 236;
  const HEADER_H = 30;
  const ROW_H = 22;
  const BODY_PAD = 4;
  const BODY_MAX_H = 264; // matches .node-body max-height (≈12 columns, then scroll)

  const dialect = $derived<Dialect | null>(
    ((e) => (e === 'mysql' || e === 'postgres' || e === 'clickhouse' ? e : null))(
      database.capabilities?.engine ?? null,
    ),
  );
  const aggs = $derived(aggregatesFor(dialect ?? 'mysql'));

  function emptyClauses(): Clauses {
    return {
      distinct: false,
      select: [],
      where: emptyGroup('AND'),
      groupBy: [],
      having: emptyGroup('AND'),
      orderBy: [],
      limit: 100,
      offset: null,
    };
  }

  // ── State ──────────────────────────────────────────────────────────────────
  let tables = $state<CardTable[]>([]);
  let edges = $state<CanvasEdge[]>([]);
  let clauses = $state<Clauses>(emptyClauses());
  let importError = $state<string | null>(null);
  let importing = $state(false);

  // Palette
  let databases = $state<{ name: string; path: string }[]>([]);
  let selectedDb = $state<string>(''); // db path
  let paletteTables = $state<{ label: string; path: string; kind: string }[]>([]);
  let paletteSearch = $state('');
  let paletteLoading = $state(false);

  // ── Split between the canvas and the clause designer (persisted) ─────────
  const CANVAS_H_KEY = 'db.qbCanvasH';
  let canvasH = $state<number | null>(loadCanvasH());
  function loadCanvasH(): number | null {
    try {
      const v = Number(localStorage.getItem(CANVAS_H_KEY));
      return Number.isFinite(v) && v >= 140 ? v : null;
    } catch {
      return null;
    }
  }
  let mainEl = $state<HTMLDivElement | null>(null);
  function startSplit(e: PointerEvent): void {
    e.preventDefault();
    const startY = e.clientY;
    const startH = canvasEl?.parentElement?.clientHeight ?? 300;
    const maxH = Math.max(160, (mainEl?.clientHeight ?? 700) - 200);
    const onMove = (ev: PointerEvent): void => {
      canvasH = Math.max(140, Math.min(maxH, startH + (ev.clientY - startY)));
    };
    const onUp = (): void => {
      try {
        if (canvasH) localStorage.setItem(CANVAS_H_KEY, String(Math.round(canvasH)));
      } catch {
        /* storage unavailable — non-fatal */
      }
      window.removeEventListener('pointermove', onMove);
      window.removeEventListener('pointerup', onUp);
    };
    window.addEventListener('pointermove', onMove);
    window.addEventListener('pointerup', onUp);
  }

  // Resizable palette column (persisted; double-click resets).
  const PALETTE_W_DEFAULT = 208;
  let paletteW = $state(loadPaletteW());
  function loadPaletteW(): number {
    try {
      const v = Number(localStorage.getItem('db.qbPaletteW'));
      return Number.isFinite(v) && v >= 160 ? Math.min(400, v) : PALETTE_W_DEFAULT;
    } catch {
      return PALETTE_W_DEFAULT;
    }
  }
  function persistPaletteW(): void {
    try {
      localStorage.setItem('db.qbPaletteW', String(Math.round(paletteW)));
    } catch {
      /* storage unavailable — non-fatal */
    }
  }
  function startPaletteResize(e: PointerEvent): void {
    e.preventDefault();
    const startX = e.clientX;
    const startW = paletteW;
    const onMove = (ev: PointerEvent): void => {
      paletteW = Math.max(160, Math.min(400, startW + (ev.clientX - startX)));
    };
    const onUp = (): void => {
      persistPaletteW();
      window.removeEventListener('pointermove', onMove);
      window.removeEventListener('pointerup', onUp);
    };
    window.addEventListener('pointermove', onMove);
    window.addEventListener('pointerup', onUp);
  }
  function resetPaletteW(): void {
    paletteW = PALETTE_W_DEFAULT;
    persistPaletteW();
  }

  // Canvas scroll container (cards + edges live in its content coordinates).
  let canvasEl = $state<HTMLDivElement | null>(null);
  // Per-card body scroll/height, so edge anchors follow a scrolled column list.
  let bodyScroll = $state<Map<string, number>>(new Map());
  let bodyHeight = $state<Map<string, number>>(new Map());
  function cardBody(node: HTMLElement, uid: string) {
    const sync = (): void => {
      bodyScroll = new Map(bodyScroll).set(uid, node.scrollTop);
      bodyHeight = new Map(bodyHeight).set(uid, node.clientHeight);
    };
    sync();
    node.addEventListener('scroll', sync, { passive: true });
    const ro = new ResizeObserver(sync);
    ro.observe(node);
    return {
      destroy() {
        node.removeEventListener('scroll', sync);
        ro.disconnect();
      },
    };
  }

  let dragUid = $state<string | null>(null);
  let dragOffX = 0;
  let dragOffY = 0;
  let pending = $state<{ fromUid: string; fromCol: string; side: 'l' | 'r' } | null>(null);
  let pendingPt = $state<{ x: number; y: number } | null>(null);
  let editEdge = $state<string | null>(null);

  // ── Per-connection persistence ─────────────────────────────────────────────
  const connKey = $derived(JSON.stringify([auth.me?.id, database.selectedConnId, database.accessRevision]));
  let restoredFor = $state<string | null>(null);
  $effect(() => {
    const key = connKey;
    if (restoredFor === key) return;
    restoredFor = key;
    const snap = builderCache.get(key);
    tables = snap?.tables ?? [];
    edges = snap?.edges ?? [];
    clauses = snap?.clauses ?? emptyClauses();
    selectedDb = snap?.selectedDb ?? '';
    if (snap?.canvasH) canvasH = snap.canvasH;
    importError = null;
  });
  $effect(() => {
    if (restoredFor !== connKey) return; // mid-switch: don't cross-save
    builderCache.set(connKey, { tables, edges, clauses, selectedDb, canvasH });
  });

  // ── Palette ─────────────────────────────────────────────────────────────────
  $effect(() => {
    void database.selectedConnId;
    void database.schemaRoot;
    void loadDatabases();
  });
  async function loadDatabases(): Promise<void> {
    if (!database.supportsBuilder) return;
    const dbs = await database.listBuilderDatabases();
    databases = dbs;
    if (dbs.length && !dbs.some((d) => d.path === selectedDb)) {
      selectedDb = (dbs.find((d) => d.name === database.activeDb) ?? dbs[0]).path;
    }
    await loadPaletteTables();
  }
  async function loadPaletteTables(): Promise<void> {
    paletteLoading = true;
    try {
      paletteTables = await database.listBuilderTables(selectedDb);
    } finally {
      paletteLoading = false;
    }
  }
  const filteredPalette = $derived.by(() => {
    const q = paletteSearch.trim().toLowerCase();
    return q ? paletteTables.filter((t) => t.label.toLowerCase().includes(q)) : paletteTables;
  });
  function dbName(path: string): string {
    return databases.find((d) => d.path === path)?.name ?? '';
  }
  const onCanvas = $derived(new Set(tables.map((t) => t.path)));

  // ── Cards ───────────────────────────────────────────────────────────────────
  function cardFrom(
    detail: ObjectDetail | null,
    base: Pick<CardTable, 'uid' | 'db' | 'table' | 'alias' | 'path' | 'x' | 'y'>,
  ): CardTable {
    return {
      ...base,
      columns: detail ? detail.columns.map((c) => ({ name: c.name, type: c.data_type })) : null,
      pk: detail?.primary_key ?? [],
      fks: (detail?.foreign_keys ?? []).map((f) => ({ columns: f.columns, ref_table: f.ref_table, ref_columns: f.ref_columns })),
    };
  }
  function nextSlot(n: number): { x: number; y: number } {
    const sx = canvasEl?.scrollLeft ?? 0;
    const sy = canvasEl?.scrollTop ?? 0;
    return { x: 24 + (n % 4) * (CARD_W + 56) + sx, y: 20 + Math.floor(n / 4) * 40 + (n % 4) * 18 + sy };
  }
  async function addTable(t: { label: string; path: string }): Promise<void> {
    const taken = new Set(tables.map((x) => x.alias));
    const alias = uniqueAlias(t.label, taken);
    const uid = nid('tbl');
    const first = tables.length === 0;
    const slot = nextSlot(tables.length);
    tables = [...tables, cardFrom(null, { uid, db: dbName(selectedDb), table: t.label, alias, path: t.path, ...slot })];
    importError = null;
    const detail = await database.fetchObject(t.path);
    tables = tables.map((c) => (c.uid === uid ? cardFrom(detail, c) : c));
    // A table dropped onto an empty builder is a "look at this table" — start
    // from all of its rows; joined tables start with nothing selected.
    if (first) clauses.select = [];
    // Offer FK joins automatically only when exactly one suggestion exists
    // for the new card: unambiguous and what the user nearly always wants.
    const mine = fkSuggestions(tables, edges).filter((s) => s.fromUid === uid || s.toUid === uid);
    if (!first && mine.length === 1) applySuggestion(mine[0]);
  }
  function removeTable(uid: string): void {
    const gone = tables.find((t) => t.uid === uid);
    tables = tables.filter((t) => t.uid !== uid);
    edges = edges.filter((e) => e.fromUid !== uid && e.toUid !== uid);
    if (gone) clauses = dropAlias(clauses, gone.alias);
  }
  function setAlias(uid: string, raw: string): void {
    const clean = raw.replace(/[^A-Za-z0-9_]/g, '_');
    const old = tables.find((t) => t.uid === uid)?.alias;
    if (old === undefined || old === clean || !clean) return;
    if (tables.some((t) => t.alias === clean)) {
      toasts.warn('Alias already used', `Another table on the canvas is already “${clean}”.`);
      return;
    }
    tables = tables.map((t) => (t.uid === uid ? { ...t, alias: clean } : t));
    clauses = renameAlias(clauses, old, clean);
  }
  function clearCanvas(): void {
    tables = [];
    edges = [];
    clauses = emptyClauses();
    importError = null;
  }

  // ── Columns on cards ↔ SELECT items ─────────────────────────────────────────
  const refKey = (r: ColRef): string => `${r.alias}.${r.column}`;
  function parseKey(k: string): ColRef {
    const i = k.indexOf('.');
    return { alias: k.slice(0, i), column: k.slice(i + 1) };
  }
  function isSelected(alias: string, column: string): boolean {
    return clauses.select.some((s) => s.kind === 'column' && s.ref.alias === alias && s.ref.column === column);
  }
  function toggleCol(alias: string, column: string): void {
    if (isSelected(alias, column)) {
      clauses.select = clauses.select.filter(
        (s) => !(s.kind === 'column' && s.ref.alias === alias && s.ref.column === column),
      );
    } else {
      clauses.select = [...clauses.select, { kind: 'column', id: nid('s'), ref: { alias, column } }];
    }
  }
  function selectAllOf(t: CardTable, on: boolean): void {
    const rest = clauses.select.filter((s) => !(s.kind === 'column' && s.ref.alias === t.alias));
    clauses.select = on
      ? [...rest, ...(t.columns ?? []).map((c): SelectItem => ({ kind: 'column', id: nid('s'), ref: { alias: t.alias, column: c.name } }))]
      : rest;
  }

  // Every column on the canvas, for the clause pickers.
  const colOptions = $derived(
    tables.flatMap((t) =>
      (t.columns ?? []).map((c) => ({ key: `${t.alias}.${c.name}`, alias: t.alias, column: c.name, type: c.type })),
    ),
  );
  const typeByKey = $derived(new Map(colOptions.map((o) => [o.key, o.type])));
  const kindOf = (r: ColRef): ReturnType<typeof valueKind> => valueKind(typeByKey.get(refKey(r)));
  const firstRef = (): ColRef | null => (colOptions[0] ? { alias: colOptions[0].alias, column: colOptions[0].column } : null);

  // ── SELECT list ─────────────────────────────────────────────────────────────
  function addColumnItem(): void {
    const r = firstRef();
    if (r) clauses.select = [...clauses.select, { kind: 'column', id: nid('s'), ref: r }];
  }
  function addAggregate(): void {
    clauses.select = [...clauses.select, { kind: 'aggregate', id: nid('s'), fn: 'COUNT', ref: null, as: 'count' }];
    autoGroup();
  }
  function addExpression(): void {
    clauses.select = [...clauses.select, { kind: 'expr', id: nid('s'), sql: '', as: '' }];
  }
  function moveSelect(i: number, d: number): void {
    const j = i + d;
    if (j < 0 || j >= clauses.select.length) return;
    const next = clauses.select.slice();
    [next[i], next[j]] = [next[j], next[i]];
    clauses.select = next;
  }
  function removeSelect(id: string): void {
    clauses.select = clauses.select.filter((s) => s.id !== id);
    clauses.orderBy = clauses.orderBy.filter((o) => !(o.target.kind === 'select' && o.target.id === id));
  }
  function setAggFn(it: Extract<SelectItem, { kind: 'aggregate' }>, fn: AggFn): void {
    const wasDefault = !it.as || it.as === defaultAggAlias(it.fn, it.ref);
    it.fn = fn;
    if (fn !== 'COUNT' && !it.ref) {
      const r = colOptions.find((o) => valueKind(o.type) === 'number') ?? colOptions[0];
      if (r) it.ref = { alias: r.alias, column: r.column };
    }
    if (wasDefault) it.as = defaultAggAlias(fn, it.ref);
  }
  function setAggArg(it: Extract<SelectItem, { kind: 'aggregate' }>, key: string): void {
    const wasDefault = !it.as || it.as === defaultAggAlias(it.fn, it.ref);
    it.ref = key === '*' ? null : parseKey(key);
    if (wasDefault) it.as = defaultAggAlias(it.fn, it.ref);
  }
  /** First aggregate on a query with plain columns and no GROUP BY yet: group
   *  by those columns (the SQL would be rejected otherwise). Visible, editable. */
  function autoGroup(): void {
    if (clauses.groupBy.length) return;
    const q = toQuery(dialect ?? 'mysql', tables, edges, clauses);
    clauses.groupBy = suggestGroupBy(q);
  }

  // ── Conditions (WHERE / HAVING) ─────────────────────────────────────────────
  function newCond(having: boolean): Condition | null {
    const r = firstRef();
    if (!r) return null;
    if (having) return { kind: 'cond', id: nid('c'), target: { ref: { ...r, column: '*' }, fn: 'COUNT' }, op: '>', value: '' };
    return { kind: 'cond', id: nid('c'), target: { ref: r }, op: opsFor(kindOf(r))[0], value: '' };
  }
  function addCond(g: CondGroup, having: boolean): void {
    const c = newCond(having);
    if (c) g.items.push(c);
  }
  function addGroup(g: CondGroup, having: boolean): void {
    const inner = emptyGroup(g.conj === 'AND' ? 'OR' : 'AND');
    const c = newCond(having);
    if (c) inner.items.push(c);
    g.items.push(inner);
  }
  function removeAt(g: CondGroup, i: number): void {
    g.items.splice(i, 1);
  }
  function condKind(c: Condition): ReturnType<typeof valueKind> {
    if (c.target.fn && c.target.fn !== 'MIN' && c.target.fn !== 'MAX') return 'number';
    return kindOf(c.target.ref);
  }
  function setCondCol(c: Condition, key: string): void {
    c.target = { ...c.target, ref: key === '*' ? { alias: c.target.ref.alias, column: '*' } : parseKey(key) };
    const allowed = opsFor(condKind(c));
    if (!allowed.includes(c.op)) c.op = allowed[0];
  }
  /** HAVING aggregate change: only COUNT takes `*`; others need a column. */
  function setHavingFn(c: Condition, fn: AggFn): void {
    let ref = c.target.ref;
    if (fn !== 'COUNT' && ref.column === '*') {
      const r = colOptions.find((o) => valueKind(o.type) === 'number') ?? colOptions[0];
      if (r) ref = { alias: r.alias, column: r.column };
    }
    c.target = { ref, fn };
  }
  function setListText(c: Condition, text: string): void {
    c.value = text;
    c.values = splitList(text);
  }
  const placeholderFor = (k: ReturnType<typeof valueKind>): string =>
    k === 'number' ? '0' : k === 'time' ? '2026-01-01' : k === 'bool' ? 'true' : 'value';
  function countConds(g: CondGroup): number {
    return g.items.reduce((n, it) => n + (it.kind === 'group' ? countConds(it) : 1), 0);
  }

  // ── GROUP BY / ORDER BY ─────────────────────────────────────────────────────
  function addGroupBy(key: string): void {
    if (!key || clauses.groupBy.some((r) => refKey(r) === key)) return;
    clauses.groupBy = [...clauses.groupBy, parseKey(key)];
  }
  function removeGroupBy(i: number): void {
    clauses.groupBy = clauses.groupBy.filter((_, j) => j !== i);
  }
  function orderKey(o: OrderItem): string {
    return o.target.kind === 'select' ? `sel:${o.target.id}` : `col:${refKey(o.target.ref)}`;
  }
  function setOrderTarget(o: OrderItem, key: string): void {
    o.target = key.startsWith('sel:') ? { kind: 'select', id: key.slice(4) } : { kind: 'column', ref: parseKey(key.slice(4)) };
  }
  function addOrder(): void {
    const agg = clauses.select.find((s) => s.kind === 'aggregate');
    const r = firstRef();
    const target: OrderItem['target'] | null = agg ? { kind: 'select', id: agg.id } : r ? { kind: 'column', ref: r } : null;
    if (target) clauses.orderBy = [...clauses.orderBy, { id: nid('o'), target, dir: agg ? 'DESC' : 'ASC', nulls: 'default' }];
  }
  function moveOrder(i: number, d: number): void {
    const j = i + d;
    if (j < 0 || j >= clauses.orderBy.length) return;
    const next = clauses.orderBy.slice();
    [next[i], next[j]] = [next[j], next[i]];
    clauses.orderBy = next;
  }
  function selectLabel(s: SelectItem): string {
    if (s.as?.trim()) return s.as.trim();
    if (s.kind === 'column') return refKey(s.ref);
    if (s.kind === 'aggregate') return `${s.fn}(${s.ref ? refKey(s.ref) : '*'})`;
    return s.sql.trim() || 'expression';
  }

  // ── Edges (drawing joins) ───────────────────────────────────────────────────
  function canvasPoint(ev: { clientX: number; clientY: number }): { x: number; y: number } {
    const rect = canvasEl?.getBoundingClientRect();
    if (!rect || !canvasEl) return { x: 0, y: 0 };
    return { x: ev.clientX - rect.left + canvasEl.scrollLeft, y: ev.clientY - rect.top + canvasEl.scrollTop };
  }
  function startDrag(ev: PointerEvent, uid: string): void {
    if (ev.button !== 0) return;
    const t = tables.find((x) => x.uid === uid);
    if (!t) return;
    const pt = canvasPoint(ev);
    dragUid = uid;
    dragOffX = pt.x - t.x;
    dragOffY = pt.y - t.y;
    (ev.currentTarget as HTMLElement).setPointerCapture?.(ev.pointerId);
    ev.preventDefault();
  }
  function startConnect(ev: PointerEvent, uid: string, col: string, side: 'l' | 'r'): void {
    if (ev.button !== 0) return;
    pending = { fromUid: uid, fromCol: col, side };
    pendingPt = canvasPoint(ev);
    canvasEl?.setPointerCapture?.(ev.pointerId);
    ev.stopPropagation();
    ev.preventDefault();
  }
  function commitConnect(uid: string, col: string): void {
    const p = pending;
    if (!p || (p.fromUid === uid && p.fromCol === col) || p.fromUid === uid) return;
    const dup = edges.some(
      (e) =>
        (e.fromUid === p.fromUid && e.fromCol === p.fromCol && e.toUid === uid && e.toCol === col) ||
        (e.fromUid === uid && e.fromCol === col && e.toUid === p.fromUid && e.toCol === p.fromCol),
    );
    if (dup) return;
    edges = [...edges, { id: nid('edge'), fromUid: p.fromUid, fromCol: p.fromCol, toUid: uid, toCol: col, type: 'INNER' }];
  }
  function onCanvasMove(ev: PointerEvent): void {
    if (dragUid) {
      const pt = canvasPoint(ev);
      const nx = Math.max(0, pt.x - dragOffX);
      const ny = Math.max(0, pt.y - dragOffY);
      tables = tables.map((t) => (t.uid === dragUid ? { ...t, x: nx, y: ny } : t));
    } else if (pending) pendingPt = canvasPoint(ev);
  }
  function onCanvasUp(ev: PointerEvent): void {
    dragUid = null;
    if (pending) {
      const el = document.elementFromPoint(ev.clientX, ev.clientY) as HTMLElement | null;
      const target = el?.closest<HTMLElement>('.handle, .col-row');
      const uid = target?.dataset.uid;
      const col = target?.dataset.col;
      if (uid && col) commitConnect(uid, col);
    }
    pending = null;
    pendingPt = null;
  }
  function colIndex(t: CardTable, col: string): number {
    return Math.max(0, (t.columns ?? []).findIndex((c) => c.name === col));
  }
  function visibleBodyH(t: CardTable): number {
    const measured = bodyHeight.get(t.uid);
    if (measured && measured > 0) return measured;
    return Math.min(BODY_MAX_H, (t.columns?.length ?? 1) * ROW_H + BODY_PAD * 2);
  }
  function handleY(t: CardTable, col: string): number {
    const bodyTop = t.y + HEADER_H;
    const y = bodyTop + BODY_PAD + colIndex(t, col) * ROW_H + ROW_H / 2 - (bodyScroll.get(t.uid) ?? 0);
    return Math.min(bodyTop + Math.max(2, visibleBodyH(t) - 2), Math.max(bodyTop + 2, y));
  }
  function isClamped(t: CardTable, col: string): boolean {
    const c = BODY_PAD + colIndex(t, col) * ROW_H + ROW_H / 2 - (bodyScroll.get(t.uid) ?? 0);
    return c < 0 || c > visibleBodyH(t);
  }
  const handleX = (t: CardTable, side: 'l' | 'r'): number => (side === 'l' ? t.x : t.x + CARD_W);
  const sideFacing = (t: CardTable, otherX: number): 'l' | 'r' => (otherX < t.x + CARD_W / 2 ? 'l' : 'r');
  function bezier(x1: number, y1: number, s1: 'l' | 'r', x2: number, y2: number, s2: 'l' | 'r'): string {
    const k = Math.max(40, Math.abs(x2 - x1) / 2);
    const c1x = s1 === 'r' ? x1 + k : x1 - k;
    const c2x = s2 === 'r' ? x2 + k : x2 - k;
    return `M ${x1} ${y1} C ${c1x} ${y1}, ${c2x} ${y2}, ${x2} ${y2}`;
  }
  const contentSize = $derived.by(() => {
    let w = 700;
    let h = 260;
    for (const t of tables) {
      w = Math.max(w, t.x + CARD_W + 60);
      h = Math.max(h, t.y + HEADER_H + BODY_PAD * 2 + Math.min(BODY_MAX_H, (t.columns?.length ?? 1) * ROW_H) + 60);
    }
    return { w, h };
  });
  const edgePaths = $derived.by(() => {
    const byUid = new Map(tables.map((t) => [t.uid, t]));
    return edges
      .map((e) => {
        const a = byUid.get(e.fromUid);
        const b = byUid.get(e.toUid);
        if (!a || !b) return null;
        const sa = sideFacing(a, b.x + CARD_W / 2);
        const sb = sideFacing(b, a.x + CARD_W / 2);
        const x1 = handleX(a, sa);
        const y1 = handleY(a, e.fromCol);
        const x2 = handleX(b, sb);
        const y2 = handleY(b, e.toCol);
        return {
          id: e.id,
          type: e.type,
          d: bezier(x1, y1, sa, x2, y2, sb),
          mx: (x1 + x2) / 2,
          my: (y1 + y2) / 2,
          offscreen: isClamped(a, e.fromCol) || isClamped(b, e.toCol),
          label: `${a.alias}.${e.fromCol} = ${b.alias}.${e.toCol}`,
        };
      })
      .filter((p): p is NonNullable<typeof p> => p !== null);
  });
  const pendingPath = $derived.by(() => {
    if (!pending || !pendingPt) return null;
    const t = tables.find((x) => x.uid === pending!.fromUid);
    if (!t) return null;
    const x1 = handleX(t, pending.side);
    return bezier(x1, handleY(t, pending.fromCol), pending.side, pendingPt.x, pendingPt.y, pendingPt.x < x1 ? 'l' : 'r');
  });
  const suggestions = $derived(fkSuggestions(tables, edges));
  function applySuggestion(s: { fromUid: string; toUid: string; pairs: [string, string][] }): void {
    edges = [
      ...edges,
      ...s.pairs.map(([a, b]): CanvasEdge => ({ id: nid('edge'), fromUid: s.fromUid, fromCol: a, toUid: s.toUid, toCol: b, type: 'INNER' })),
    ];
  }
  function edgeMenu(e: MouseEvent, id: string): void {
    const edge = edges.find((x) => x.id === id);
    if (!edge) return;
    ctxMenu.show(e, [
      ...JOIN_TYPES.map((t) => ({
        label: `${t === 'FULL' ? 'FULL OUTER' : t} JOIN${edge.type === t ? '  ✓' : ''}`,
        action: () => (edges = edges.map((x) => (x.id === id ? { ...x, type: t } : x))),
      })),
      { separator: true },
      { label: 'Remove join', icon: 'trash', danger: true, action: () => (edges = edges.filter((x) => x.id !== id)) },
    ]);
  }

  // ── Generated SQL ───────────────────────────────────────────────────────────
  const unreached = $derived(tables.length > 1 ? walkCanvas(tables, edges).unreached : []);
  const query = $derived(dialect ? toQuery(dialect, tables, edges, clauses) : null);
  const sql = $derived(query ? buildSelect(query) : '');
  const issues = $derived(query ? validate(query) : []);
  const hasErrors = $derived(issues.some((i) => i.level === 'error'));

  /** Cheap SQL highlighter for the preview (keywords, strings, names, numbers). */
  const KW = /^(SELECT|DISTINCT|FROM|WHERE|AND|OR|NOT|IN|IS|NULL|LIKE|BETWEEN|GROUP|BY|HAVING|ORDER|ASC|DESC|NULLS|FIRST|LAST|LIMIT|OFFSET|AS|ON|INNER|LEFT|RIGHT|FULL|OUTER|CROSS|JOIN|TRUE|FALSE|COUNT|SUM|AVG|MIN|MAX|GROUP_CONCAT|STRING_AGG|uniqExact|uniq|groupArray)$/;
  const sqlTokens = $derived.by(() => {
    const out: { t: string; c: string }[] = [];
    const re = /('(?:[^'\\]|\\.|'')*')|(`(?:[^`]|``)*`|"(?:[^"]|"")*")|(\b\d+(?:\.\d+)?\b)|([A-Za-z_][A-Za-z0-9_]*)|(\s+|.)/g;
    let m: RegExpExecArray | null;
    while ((m = re.exec(sql))) {
      if (m[1]) out.push({ t: m[1], c: 'str' });
      else if (m[2]) out.push({ t: m[2], c: 'id' });
      else if (m[3]) out.push({ t: m[3], c: 'num' });
      else if (m[4]) out.push({ t: m[4], c: KW.test(m[4]) ? 'kw' : '' });
      else out.push({ t: m[5], c: '' });
    }
    return out;
  });

  const canRun = $derived(
    !!database.selectedConnId &&
      resourceAccess.can('connection', database.selectedConnId, 'db_query', 'database', 'edit', databaseAccessChild(selectedDb || database.activeDb)),
  );
  $effect(() => {
    if (database.selectedConnId) void resourceAccess.load('connection', database.selectedConnId, databaseAccessChild(selectedDb || database.activeDb));
  });
  function openInQuery(andRun: boolean): void {
    if (!sql || (andRun && (!canRun || hasErrors))) return;
    database.newTab(sql);
    if (andRun) void database.runQuery(sql);
  }
  async function copySql(): Promise<void> {
    try {
      await navigator.clipboard.writeText(sql);
      toasts.success('Copied', 'Generated SQL copied');
    } catch {
      toasts.error('Copy failed');
    }
  }

  // ── Round trip: a statement handed over from a query tab ─────────────────────
  $effect(() => {
    const imp = database.builderImport;
    if (!imp || !dialect || restoredFor !== connKey) return;
    if (imp.connId !== database.selectedConnId) return;
    database.builderImport = null;
    void importSql(imp.sql);
  });
  async function importSql(text: string): Promise<void> {
    if (!dialect) return;
    const r = parseSelect(text, dialect);
    if (!r.ok) {
      importError = `This statement can't be edited in the builder: ${r.error}.`;
      return;
    }
    importing = true;
    importError = null;
    try {
      if (!databases.length) databases = await database.listBuilderDatabases();
      const q = r.query;
      const srcs = [q.from!, ...q.joins.map((j) => j.table)];
      const cards: CardTable[] = [];
      for (const [i, s] of srcs.entries()) {
        const want = s.schema ?? database.activeDb ?? dbName(selectedDb);
        const dbPath = databases.find((d) => d.name === want)?.path ?? selectedDb;
        const list = await database.listBuilderTables(dbPath);
        const hit = list.find((t) => t.label === s.table);
        if (!hit) {
          importError = `Table “${s.table}” was not found in ${want || 'this database'}.`;
          return;
        }
        const detail = await database.fetchObject(hit.path);
        cards.push(
          cardFrom(detail, {
            uid: nid('tbl'),
            db: s.schema ?? '',
            table: s.table,
            alias: s.alias,
            path: hit.path,
            x: 24 + i * (CARD_W + 64),
            y: 20 + (i % 2) * 24,
          }),
        );
      }
      const uidOf = new Map(cards.map((c) => [c.alias, c.uid]));
      const newEdges: CanvasEdge[] = [];
      for (const j of q.joins) {
        for (const p of j.on) {
          const a = uidOf.get(p.left.alias);
          const b = uidOf.get(p.right.alias);
          if (a && b) newEdges.push({ id: nid('edge'), fromUid: a, fromCol: p.left.column, toUid: b, toCol: p.right.column, type: j.type });
        }
      }
      tables = cards;
      edges = newEdges;
      clauses = {
        distinct: q.distinct,
        select: q.select,
        where: q.where,
        groupBy: q.groupBy,
        having: q.having,
        orderBy: q.orderBy,
        limit: q.limit,
        offset: q.offset,
      };
      toasts.success('Opened in Builder', 'The statement is now editable visually.');
    } finally {
      importing = false;
    }
  }
</script>

{#if !database.supportsBuilder || !dialect}
  <EmptyState
    icon="layers"
    title="Builder unavailable"
    body="The visual query builder works with MySQL, PostgreSQL and ClickHouse connections. For MongoDB, use Aggregate pipeline… in the results toolbar's More menu."
  />
{:else}
  <div class="builder" style="--qb-palette-w:{paletteW}px">
    <!-- ── Palette ─────────────────────────────────────────────────────── -->
    <aside class="palette" aria-label="Tables">
      <div class="pal-head">
        <span class="section-title">Tables</span>
        {#if tables.length}
          <button class="icon-btn" onclick={clearCanvas} aria-label="Clear the builder" title="Clear the builder">
            <Icon name="trash" size={12} />
          </button>
        {/if}
      </div>
      {#if databases.length > 1 || (databases[0]?.name ?? '') !== ''}
        <select class="input db-select" bind:value={selectedDb} onchange={loadPaletteTables} aria-label="Database">
          {#each databases as d (d.path)}
            <option value={d.path}>{d.name || 'default'}</option>
          {/each}
        </select>
      {/if}
      <div class="pal-search">
        <Icon name="search" size={12} />
        <input class="pal-search-input" placeholder="Filter tables…" aria-label="Filter tables" bind:value={paletteSearch} spellcheck="false" />
      </div>
      <div class="pal-list">
        {#if paletteLoading}
          <div class="pal-hint">Loading tables…</div>
        {:else if paletteTables.length === 0}
          <div class="pal-hint">No tables in {dbName(selectedDb) || 'this database'}.</div>
        {:else if filteredPalette.length === 0}
          <div class="pal-hint">No tables match “{paletteSearch.trim()}”.</div>
        {:else}
          {#each filteredPalette as t (t.path)}
            <button class="pal-item" class:on={onCanvas.has(t.path)} onclick={() => addTable(t)} title="Add {t.label} to the canvas">
              <Icon name={t.kind === 'view' ? 'eye' : 'grid'} size={12} />
              <span class="pal-item-label">{t.label}</span>
              <Icon name="plus" size={11} />
            </button>
          {/each}
        {/if}
      </div>
    </aside>

    <!-- svelte-ignore a11y_no_static_element_interactions -->
    <div
      class="side-resizer"
      role="separator"
      aria-orientation="vertical"
      aria-label="Drag to resize the table list (double-click to reset)"
      title="Drag to resize · double-click to reset"
      ondblclick={resetPaletteW}
      onpointerdown={startPaletteResize}
    ></div>

    <div class="main" bind:this={mainEl}>
      <!-- ── Canvas ──────────────────────────────────────────────────────── -->
      <div class="canvas" style={canvasH ? `flex: 0 0 ${canvasH}px` : ''}>
        <!-- svelte-ignore a11y_no_static_element_interactions -->
        <div
          class="canvas-scroll"
          class:dragging={dragUid !== null || pending !== null}
          role="application"
          aria-label="Join canvas — drag from one column's dot to another table's column to join"
          bind:this={canvasEl}
          onpointermove={onCanvasMove}
          onpointerup={onCanvasUp}
          onpointercancel={onCanvasUp}
        >
          <div class="content" style="width:{contentSize.w}px; height:{contentSize.h}px">
            <svg class="edges" width={contentSize.w} height={contentSize.h} aria-hidden="true">
              <defs>
                <marker id="qb-arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
                  <path d="M0 0 L10 5 L0 10 z" fill="var(--accent)" />
                </marker>
              </defs>
              {#each edgePaths as p (p.id)}
                <path class="edge" class:active={editEdge === p.id} class:offscreen={p.offscreen} d={p.d} marker-end="url(#qb-arrow)" />
              {/each}
              {#if pendingPath}<path class="edge pending" d={pendingPath} marker-end="url(#qb-arrow)" />{/if}
            </svg>
            <!-- Join badges: a real button on each edge (type + menu). -->
            {#each edgePaths as p (p.id)}
              <button
                class="edge-badge"
                style="left:{p.mx}px; top:{p.my}px"
                onclick={(e) => edgeMenu(e, p.id)}
                onfocus={() => (editEdge = p.id)}
                onblur={() => (editEdge = null)}
                aria-label="{p.type} join {p.label} — change type or remove"
                title="{p.label} — click to change the join type or remove it"
              >{p.type === 'FULL' ? 'FULL' : p.type}</button>
            {/each}

            {#each tables as t, ti (t.uid)}
              {@const nSel = clauses.select.filter((s) => s.kind === 'column' && s.ref.alias === t.alias).length}
              <div class="node" class:base={ti === 0} style="left:{t.x}px; top:{t.y}px; width:{CARD_W}px">
                <!-- svelte-ignore a11y_no_static_element_interactions -->
                <div class="node-head" onpointerdown={(e) => startDrag(e, t.uid)}>
                  <input
                    class="node-all"
                    type="checkbox"
                    checked={!!t.columns && nSel === t.columns.length && nSel > 0}
                    onpointerdown={(e) => e.stopPropagation()}
                    onchange={(e) => selectAllOf(t, e.currentTarget.checked)}
                    aria-label="Select every column of {t.alias}"
                    title="Select every column"
                  />
                  <input
                    class="alias-input mono"
                    value={t.alias}
                    aria-label="Alias for {t.table}"
                    title="Alias — rename to change how the SQL refers to this table"
                    onpointerdown={(e) => e.stopPropagation()}
                    onchange={(e) => setAlias(t.uid, e.currentTarget.value)}
                    spellcheck="false"
                  />
                  <span class="node-src mono" title="{t.db ? `${t.db}.` : ''}{t.table}">{t.alias !== t.table ? t.table : ''}</span>
                  {#if ti === 0}<span class="node-base" title="The first table is the FROM table">FROM</span>{/if}
                  <button class="icon-btn node-x" aria-label="Remove {t.alias} from the canvas" title="Remove table" onpointerdown={(e) => e.stopPropagation()} onclick={() => removeTable(t.uid)}>
                    <Icon name="x" size={11} />
                  </button>
                </div>
                <div class="node-body" use:cardBody={t.uid}>
                  {#if !t.columns}
                    <div class="node-loading">Loading columns…</div>
                  {:else}
                    {#each t.columns as c (c.name)}
                      {@const pk = t.pk.includes(c.name)}
                      {@const fk = t.fks.some((f) => f.columns.includes(c.name))}
                      <div class="col-row" data-uid={t.uid} data-col={c.name} style="height:{ROW_H}px">
                        <!-- svelte-ignore a11y_no_static_element_interactions -->
                        <span class="handle l" data-uid={t.uid} data-col={c.name} onpointerdown={(e) => startConnect(e, t.uid, c.name, 'l')}></span>
                        <input
                          class="col-cb"
                          type="checkbox"
                          checked={isSelected(t.alias, c.name)}
                          onchange={() => toggleCol(t.alias, c.name)}
                          aria-label="Select {t.alias}.{c.name}"
                        />
                        <span class="col-name mono" class:pk class:fk title={c.name}>{c.name}</span>
                        <span class="col-ty mono" title={c.type}>{c.type}</span>
                        {#if pk}<span class="col-badge pk" title="Primary key">PK</span>{:else if fk}<span class="col-badge fk" title="Foreign key">FK</span>{:else}<span class="col-badge"></span>{/if}
                        <!-- svelte-ignore a11y_no_static_element_interactions -->
                        <span class="handle r" data-uid={t.uid} data-col={c.name} onpointerdown={(e) => startConnect(e, t.uid, c.name, 'r')}></span>
                      </div>
                    {/each}
                  {/if}
                </div>
              </div>
            {/each}
          </div>
        </div>

        {#if tables.length === 0}
          <div class="canvas-hint">
            <Icon name="layers" size={22} />
            <p class="ch-title">Build a query visually</p>
            <p>Pick a table on the left. Add more and drag between columns to join — or right-click a query tab and choose <strong>Open in Builder</strong>.</p>
          </div>
        {/if}
        {#if suggestions.length || unreached.length}
          <div class="canvas-bar">
            {#if unreached.length}
              <span class="cb-warn"><Icon name="warning" size={11} />Not joined — left out of the SQL: {unreached.map((t) => t.alias).join(', ')}</span>
            {/if}
            {#each suggestions as s (s.label)}
              <button class="fk-chip" onclick={() => applySuggestion(s)} title="Join on this foreign key">
                <Icon name="merge" size={11} />{s.label}
              </button>
            {/each}
          </div>
        {/if}
      </div>

      <!-- svelte-ignore a11y_no_static_element_interactions -->
      <div class="split" role="separator" aria-orientation="horizontal" aria-label="Drag to resize the canvas" title="Drag to resize" onpointerdown={startSplit}>
        <span class="grip"></span>
      </div>

      <!-- ── Designer: clauses + SQL ─────────────────────────────────────── -->
      <div class="designer">
        <div class="clauses" class:disabled={tables.length === 0}>
          {#if importError}
            <div class="notice err" role="alert">
              <Icon name="warning" size={12} />
              <span>{importError}</span>
              <button class="icon-btn" onclick={() => (importError = null)} aria-label="Dismiss" title="Dismiss"><Icon name="x" size={11} /></button>
            </div>
          {/if}
          {#if importing}<div class="notice">Opening the statement…</div>{/if}

          <!-- Columns -->
          <section class="sec" aria-labelledby="qb-cols">
            <header class="sec-head">
              <h3 id="qb-cols" class="section-title">Columns</h3>
              <span class="sec-count">{clauses.select.length || 'all (*)'}</span>
              <label class="distinct"><input type="checkbox" bind:checked={clauses.distinct} /> Distinct</label>
              <span class="grow"></span>
              <button class="btn small ghost" onclick={addColumnItem} disabled={!colOptions.length}><Icon name="plus" size={11} />Column</button>
              <button class="btn small ghost" onclick={addAggregate} disabled={!colOptions.length}><Icon name="sigma" size={11} />Aggregate</button>
              <button class="btn small ghost" onclick={addExpression} disabled={!colOptions.length}><Icon name="function" size={11} />Expression</button>
            </header>
            {#if clauses.select.length === 0}
              <p class="sec-hint">Every column (<code>*</code>). Tick columns on the cards, or add columns and aggregates here.</p>
            {/if}
            {#each clauses.select as it, i (it.id)}
              <div class="row sel-row">
                <span class="ord">{i + 1}</span>
                {#if it.kind === 'column'}
                  <select class="input grow-2" value={refKey(it.ref)} onchange={(e) => (it.ref = parseKey(e.currentTarget.value))} aria-label="Column">
                    {#each colOptions as o (o.key)}<option value={o.key}>{o.key}</option>{/each}
                  </select>
                {:else if it.kind === 'aggregate'}
                  <select class="input fn" value={it.fn} onchange={(e) => setAggFn(it, e.currentTarget.value as AggFn)} aria-label="Aggregate">
                    {#each aggs as a (a.fn)}<option value={a.fn}>{a.label}</option>{/each}
                  </select>
                  <select class="input grow-2" value={it.ref ? refKey(it.ref) : '*'} onchange={(e) => setAggArg(it, e.currentTarget.value)} aria-label="Aggregate of">
                    {#if it.fn === 'COUNT'}<option value="*">* (rows)</option>{/if}
                    {#each colOptions as o (o.key)}<option value={o.key}>{o.key}</option>{/each}
                  </select>
                {:else}
                  <input class="input mono grow-2" bind:value={it.sql} placeholder={dialect === 'postgres' ? "CASE WHEN total > 100 THEN 'big' END" : "IF(total > 100, 'big', 'small')"} aria-label="SQL expression" spellcheck="false" />
                {/if}
                <span class="as">AS</span>
                <input class="input mono alias" bind:value={it.as} placeholder={it.kind === 'column' ? it.ref.column : 'alias'} aria-label="Output name" spellcheck="false" />
                <button class="icon-btn" onclick={() => moveSelect(i, -1)} disabled={i === 0} aria-label="Move up" title="Move up"><Icon name="chevronUp" size={12} /></button>
                <button class="icon-btn" onclick={() => moveSelect(i, 1)} disabled={i === clauses.select.length - 1} aria-label="Move down" title="Move down"><Icon name="chevronDown" size={12} /></button>
                <button class="icon-btn" onclick={() => removeSelect(it.id)} aria-label="Remove column" title="Remove"><Icon name="x" size={12} /></button>
              </div>
            {/each}
          </section>

          <!-- WHERE -->
          <section class="sec" aria-labelledby="qb-where">
            <header class="sec-head">
              <h3 id="qb-where" class="section-title">Filters</h3>
              <span class="sec-count">{countConds(clauses.where) || ''}</span>
              <span class="grow"></span>
              <button class="btn small ghost" onclick={() => addCond(clauses.where, false)} disabled={!colOptions.length}><Icon name="plus" size={11} />Condition</button>
              <button class="btn small ghost" onclick={() => addGroup(clauses.where, false)} disabled={!colOptions.length}><Icon name="plus" size={11} />Group</button>
            </header>
            {#if clauses.where.items.length === 0}
              <p class="sec-hint">No filters — every row.</p>
            {:else}
              {@render groupEditor(clauses.where, 0, false)}
            {/if}
          </section>

          <!-- GROUP BY -->
          <section class="sec" aria-labelledby="qb-group">
            <header class="sec-head">
              <h3 id="qb-group" class="section-title">Group by</h3>
              <span class="grow"></span>
              <select
                class="input add-select"
                value=""
                onchange={(e) => {
                  addGroupBy(e.currentTarget.value);
                  e.currentTarget.value = '';
                }}
                aria-label="Add a GROUP BY column"
                disabled={!colOptions.length}
              >
                <option value="">+ Column…</option>
                {#each colOptions as o (o.key)}<option value={o.key}>{o.key}</option>{/each}
              </select>
            </header>
            {#if clauses.groupBy.length === 0}
              <p class="sec-hint">No grouping. Adding an aggregate groups by the other selected columns.</p>
            {:else}
              <div class="chips">
                {#each clauses.groupBy as r, i (refKey(r))}
                  <span class="chip mono">{refKey(r)}<button class="chip-x" onclick={() => removeGroupBy(i)} aria-label="Remove {refKey(r)} from GROUP BY" title="Remove"><Icon name="x" size={9} /></button></span>
                {/each}
              </div>
            {/if}
          </section>

          <!-- HAVING -->
          <section class="sec" aria-labelledby="qb-having">
            <header class="sec-head">
              <h3 id="qb-having" class="section-title">Having</h3>
              <span class="sec-count">{countConds(clauses.having) || ''}</span>
              <span class="grow"></span>
              <button class="btn small ghost" onclick={() => addCond(clauses.having, true)} disabled={!colOptions.length}><Icon name="plus" size={11} />Condition</button>
            </header>
            {#if clauses.having.items.length === 0}
              <p class="sec-hint">Filter the groups, e.g. COUNT(*) &gt; 10.</p>
            {:else}
              {@render groupEditor(clauses.having, 0, true)}
            {/if}
          </section>

          <!-- ORDER BY -->
          <section class="sec" aria-labelledby="qb-order">
            <header class="sec-head">
              <h3 id="qb-order" class="section-title">Sort</h3>
              <span class="grow"></span>
              <button class="btn small ghost" onclick={addOrder} disabled={!colOptions.length}><Icon name="plus" size={11} />Sort</button>
            </header>
            {#if clauses.orderBy.length === 0}
              <p class="sec-hint">Unsorted — the engine picks the order.</p>
            {/if}
            {#each clauses.orderBy as o, i (o.id)}
              <div class="row">
                <span class="ord">{i + 1}</span>
                <select class="input grow-2" value={orderKey(o)} onchange={(e) => setOrderTarget(o, e.currentTarget.value)} aria-label="Sort by">
                  {#if clauses.select.length}
                    <optgroup label="Output columns">
                      {#each clauses.select as s (s.id)}<option value="sel:{s.id}">{selectLabel(s)}</option>{/each}
                    </optgroup>
                  {/if}
                  <optgroup label="Table columns">
                    {#each colOptions as c (c.key)}<option value="col:{c.key}">{c.key}</option>{/each}
                  </optgroup>
                </select>
                <div class="segmented dir" role="group" aria-label="Direction">
                  <button class:active={o.dir === 'ASC'} aria-pressed={o.dir === 'ASC'} onclick={() => (o.dir = 'ASC')}>Asc</button>
                  <button class:active={o.dir === 'DESC'} aria-pressed={o.dir === 'DESC'} onclick={() => (o.dir = 'DESC')}>Desc</button>
                </div>
                <select class="input nulls" bind:value={o.nulls} aria-label="NULLs position" title={dialect === 'mysql' ? 'MySQL has no NULLS FIRST/LAST — emulated with an IS NULL sort key' : 'NULLS FIRST / LAST'}>
                  <option value="default">NULLs: default</option>
                  <option value="first">NULLs first</option>
                  <option value="last">NULLs last</option>
                </select>
                <button class="icon-btn" onclick={() => moveOrder(i, -1)} disabled={i === 0} aria-label="Move up" title="Move up"><Icon name="chevronUp" size={12} /></button>
                <button class="icon-btn" onclick={() => moveOrder(i, 1)} disabled={i === clauses.orderBy.length - 1} aria-label="Move down" title="Move down"><Icon name="chevronDown" size={12} /></button>
                <button class="icon-btn" onclick={() => (clauses.orderBy = clauses.orderBy.filter((x) => x.id !== o.id))} aria-label="Remove sort" title="Remove"><Icon name="x" size={12} /></button>
              </div>
            {/each}
          </section>

          <!-- LIMIT / OFFSET -->
          <section class="sec limits" aria-label="Limit and offset">
            <label class="lim"><span class="section-title">Limit</span>
              <input
                class="input mono"
                type="number"
                min="0"
                value={clauses.limit ?? ''}
                placeholder="none"
                oninput={(e) => (clauses.limit = e.currentTarget.value === '' ? null : Math.max(0, Number(e.currentTarget.value)))}
              />
            </label>
            <label class="lim"><span class="section-title">Offset</span>
              <input
                class="input mono"
                type="number"
                min="0"
                value={clauses.offset ?? ''}
                placeholder="0"
                oninput={(e) => (clauses.offset = e.currentTarget.value === '' ? null : Math.max(0, Number(e.currentTarget.value)))}
              />
            </label>
          </section>
        </div>

        <!-- SQL preview -->
        <div class="sql-pane" aria-label="Generated SQL">
          <header class="sql-head">
            <span class="section-title">SQL</span>
            <span class="sql-dialect mono">{dialect}</span>
            <span class="grow"></span>
            <button class="icon-btn" onclick={copySql} disabled={!sql} aria-label="Copy SQL" title="Copy SQL"><Icon name="copy" size={12} /></button>
          </header>
          {#if issues.length}
            <ul class="issues">
              {#each issues as is (is.message)}
                <li class:err={is.level === 'error'}>
                  <Icon name="warning" size={11} />
                  <span>{is.message}</span>
                  {#if is.fix?.kind === 'group-by'}
                    {@const refs = is.fix.refs}
                    <button class="btn small ghost" onclick={() => (clauses.groupBy = [...clauses.groupBy, ...refs])}>Group by {refs.length === 1 ? 'it' : 'them'}</button>
                  {/if}
                </li>
              {/each}
            </ul>
          {/if}
          <pre class="sql mono" data-testid="qb-sql">{#if sql}{#each sqlTokens as tok, ti (ti)}<span class={tok.c}>{tok.t}</span>{/each}{:else}<span class="sql-empty">Add a table to start.</span>{/if}</pre>
          <footer class="sql-actions">
            <button class="btn small" onclick={() => openInQuery(false)} disabled={!sql} title="Open the SQL in a new query tab to keep editing by hand (not run)">
              <Icon name="external" size={11} />Open in editor
            </button>
            <button
              class="btn small primary"
              onclick={() => openInQuery(true)}
              disabled={!sql || !canRun || hasErrors}
              title={hasErrors ? 'Fix the errors above first' : !canRun ? 'You do not have query access on this connection' : 'Run in a new query tab'}
            >
              <Icon name="play" size={11} />Run
            </button>
          </footer>
        </div>
      </div>
    </div>
  </div>
{/if}

{#snippet groupEditor(g: CondGroup, depth: number, having: boolean)}
  <div class="cgroup" class:nested={depth > 0}>
    {#if g.items.length > 1 || depth > 0}
      <div class="cg-head">
        <div class="segmented conj" role="group" aria-label="Combine conditions with">
          <button class:active={g.conj === 'AND'} aria-pressed={g.conj === 'AND'} onclick={() => (g.conj = 'AND')} title="All must match">AND</button>
          <button class:active={g.conj === 'OR'} aria-pressed={g.conj === 'OR'} onclick={() => (g.conj = 'OR')} title="Any may match">OR</button>
        </div>
        <span class="cg-hint">{g.conj === 'AND' ? 'all of' : 'any of'}</span>
        {#if depth > 0}
          <span class="grow"></span>
          <button class="btn small ghost" onclick={() => addCond(g, having)}><Icon name="plus" size={10} />Condition</button>
        {/if}
      </div>
    {/if}
    {#each g.items as it, i (it.id)}
      {#if it.kind === 'group'}
        <div class="cg-item">
          {@render groupEditor(it, depth + 1, having)}
          <button class="icon-btn cg-x" onclick={() => removeAt(g, i)} aria-label="Remove group" title="Remove group"><Icon name="x" size={12} /></button>
        </div>
      {:else}
        {@const k = condKind(it)}
        {@const ar = OPS[it.op].arity}
        <div class="row cond">
          {#if having}
            <select class="input fn" value={it.target.fn ?? 'COUNT'} onchange={(e) => setHavingFn(it, e.currentTarget.value as AggFn)} aria-label="Aggregate">
              {#each aggs as a (a.fn)}<option value={a.fn}>{a.label}</option>{/each}
            </select>
          {/if}
          <select class="input col" value={it.target.ref.column === '*' ? '*' : refKey(it.target.ref)} onchange={(e) => setCondCol(it, e.currentTarget.value)} aria-label="Column">
            {#if having && (it.target.fn ?? 'COUNT') === 'COUNT'}<option value="*">* (rows)</option>{/if}
            {#each colOptions as o (o.key)}<option value={o.key}>{o.key}</option>{/each}
          </select>
          <select class="input op" value={it.op} onchange={(e) => (it.op = e.currentTarget.value as Op)} aria-label="Operator">
            {#each opsFor(k) as op (op)}<option value={op}>{OPS[op].label}</option>{/each}
          </select>
          {#if ar === 1}
            <input class="input mono val" bind:value={it.value} placeholder={placeholderFor(k)} aria-label="Value" spellcheck="false" />
          {:else if ar === 2}
            <input class="input mono val half" bind:value={it.value} placeholder={placeholderFor(k)} aria-label="From" spellcheck="false" />
            <span class="as">and</span>
            <input class="input mono val half" bind:value={it.value2} placeholder={placeholderFor(k)} aria-label="To" spellcheck="false" />
          {:else if ar === 'list'}
            <input
              class="input mono val"
              value={it.value ?? (it.values ?? []).join(', ')}
              oninput={(e) => setListText(it, e.currentTarget.value)}
              placeholder="a, b, 'c, d'"
              aria-label="Values, comma-separated"
              title="Comma-separated; quote an item that contains a comma"
              spellcheck="false"
            />
          {:else}
            <span class="val none"></span>
          {/if}
          <button class="icon-btn" onclick={() => removeAt(g, i)} aria-label="Remove condition" title="Remove"><Icon name="x" size={12} /></button>
        </div>
      {/if}
    {/each}
  </div>
{/snippet}

<style>
  .builder {
    height: 100%;
    display: grid;
    grid-template-columns: var(--qb-palette-w, 208px) minmax(0, 1fr);
    overflow: hidden;
    min-height: 0;
  }
  .side-resizer {
    grid-column: 1;
    grid-row: 1;
    justify-self: end;
    width: 5px;
    margin-inline-end: -3px;
    cursor: col-resize;
    position: relative;
    z-index: 2;
    touch-action: none;
  }
  .side-resizer:hover {
    background: color-mix(in srgb, var(--accent) 45%, transparent);
  }

  /* ── Palette ── */
  .palette {
    grid-column: 1;
    grid-row: 1;
    display: flex;
    flex-direction: column;
    gap: 8px;
    padding: 10px 8px 10px 10px;
    border-inline-end: 1px solid var(--border);
    min-height: 0;
  }
  .pal-head {
    display: flex;
    align-items: center;
    justify-content: space-between;
    min-height: 24px;
  }
  .db-select {
    width: 100%;
  }
  .pal-search {
    display: flex;
    align-items: center;
    gap: 6px;
    height: 27px;
    padding: 0 8px;
    border-radius: var(--radius-s);
    border: 1px solid var(--border);
    background: var(--surface-2);
    color: var(--text-dim);
  }
  .pal-search:focus-within {
    border-color: var(--accent);
  }
  .pal-search-input {
    flex: 1;
    min-width: 0;
    border: none;
    background: transparent;
    color: var(--text);
    font-size: var(--fs-s);
    outline: none;
  }
  .pal-list {
    flex: 1;
    min-height: 0;
    overflow-y: auto;
    display: flex;
    flex-direction: column;
    gap: 1px;
  }
  .pal-item {
    display: flex;
    align-items: center;
    gap: 7px;
    width: 100%;
    height: 26px;
    padding: 0 8px;
    border: none;
    border-radius: var(--radius-s);
    background: transparent;
    color: var(--text);
    font-size: var(--fs-s);
    cursor: pointer;
    text-align: start;
  }
  .pal-item:hover {
    background: var(--hover);
  }
  .pal-item:focus-visible {
    outline: 1.5px solid var(--accent);
    outline-offset: -1.5px;
  }
  .pal-item.on {
    color: var(--accent-text);
  }
  .pal-item :global(svg:first-child) {
    color: var(--text-dim);
    flex-shrink: 0;
  }
  .pal-item-label {
    flex: 1;
    min-width: 0;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
  .pal-item :global(svg:last-child) {
    color: var(--accent-text);
    opacity: 0;
    flex-shrink: 0;
  }
  .pal-item:hover :global(svg:last-child),
  .pal-item:focus-visible :global(svg:last-child) {
    opacity: 1;
  }
  .pal-hint {
    padding: 8px;
    font-size: var(--fs-s);
    color: var(--text-dim);
  }

  /* ── Main column: canvas / split / designer ── */
  .main {
    grid-column: 2;
    grid-row: 1;
    display: flex;
    flex-direction: column;
    min-height: 0;
    min-width: 0;
    /* The designer stacks against the builder's own width (see below). */
    container-type: inline-size;
  }
  .canvas {
    position: relative;
    flex: 0 0 38%;
    min-height: 140px;
    overflow: hidden;
  }
  .canvas-scroll {
    position: absolute;
    inset: 0;
    overflow: auto;
    background: radial-gradient(circle, color-mix(in srgb, var(--text-dim) 20%, transparent) 1px, transparent 1px);
    background-size: 18px 18px;
    background-color: var(--bg);
    touch-action: none;
  }
  .canvas-scroll.dragging {
    user-select: none;
    cursor: grabbing;
  }
  .content {
    position: relative;
  }
  .edges {
    position: absolute;
    top: 0;
    left: 0;
    pointer-events: none;
    z-index: 1;
  }
  .edge {
    fill: none;
    stroke: var(--accent);
    stroke-width: 1.6;
    opacity: 0.85;
  }
  .edge.active {
    stroke-width: 2.6;
    opacity: 1;
  }
  .edge.pending {
    stroke-dasharray: 5 4;
    opacity: 0.7;
  }
  .edge.offscreen {
    stroke-dasharray: 3 3;
    opacity: 0.5;
  }
  .edge-badge {
    position: absolute;
    z-index: 4;
    transform: translate(-50%, -50%);
    height: 18px;
    padding: 0 6px;
    border: 1px solid color-mix(in srgb, var(--accent) 50%, var(--border));
    border-radius: 999px;
    background: var(--surface);
    color: var(--accent-text);
    font-size: var(--fs-xs);
    font-weight: 600;
    cursor: pointer;
  }
  .edge-badge:hover,
  .edge-badge:focus-visible {
    background: var(--accent-soft);
    outline: none;
  }

  .node {
    position: absolute;
    z-index: 2;
    border: 1px solid var(--border);
    border-radius: var(--radius-m);
    background: var(--surface);
    box-shadow: var(--shadow);
    overflow: hidden;
  }
  .node.base {
    border-color: var(--border-strong);
  }
  .node-head {
    display: flex;
    align-items: center;
    gap: 6px;
    height: 30px;
    padding: 0 4px 0 8px;
    background: var(--surface-2);
    border-bottom: 1px solid var(--border);
    cursor: grab;
  }
  .node-head:active {
    cursor: grabbing;
  }
  .node-all,
  .col-cb {
    accent-color: var(--accent);
    margin: 0;
    cursor: pointer;
    flex-shrink: 0;
  }
  .alias-input {
    width: 96px;
    min-width: 0;
    height: 22px;
    padding: 0 5px;
    border: 1px solid transparent;
    border-radius: var(--radius-s);
    background: transparent;
    color: var(--text);
    font-size: var(--fs-s);
    font-weight: 600;
    outline: none;
  }
  .alias-input:hover {
    border-color: var(--border);
  }
  .alias-input:focus {
    border-color: var(--accent);
    background: var(--surface);
  }
  .node-src {
    flex: 1;
    min-width: 0;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    font-size: var(--fs-xs);
    color: var(--text-dim);
  }
  .node-base {
    font-size: var(--fs-xs);
    font-weight: 600;
    color: var(--text-dim);
    padding: 0 5px;
    border-radius: 999px;
    border: 1px solid var(--border);
  }
  .node-x {
    width: 20px;
    height: 20px;
  }
  .node-body {
    padding: 4px 0;
    max-height: 264px;
    overflow-y: auto;
  }
  .node-loading {
    padding: 6px 12px;
    font-size: var(--fs-xs);
    color: var(--text-dim);
  }
  .col-row {
    position: relative;
    display: grid;
    grid-template-columns: auto minmax(0, 1fr) auto 22px;
    align-items: center;
    column-gap: 6px;
    padding: 0 10px;
  }
  .col-row:hover {
    background: var(--hover);
  }
  .col-name {
    min-width: 0;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    font-size: var(--fs-xs);
  }
  .col-name.pk,
  .col-name.fk {
    font-weight: 600;
  }
  .col-ty {
    max-width: 78px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    font-size: var(--fs-xs);
    color: var(--text-dim);
    text-align: end;
  }
  .col-badge {
    justify-self: end;
    font-size: var(--fs-xs);
    font-weight: 600;
    line-height: 14px;
    padding: 0 3px;
    border-radius: var(--radius-s);
  }
  .col-badge.pk {
    background: var(--accent-soft);
    color: var(--accent-text);
  }
  .col-badge.fk {
    background: var(--surface-2);
    color: var(--text-dim);
  }
  .handle {
    position: absolute;
    top: 50%;
    width: 10px;
    height: 10px;
    margin-top: -5px;
    border-radius: 50%;
    background: var(--surface);
    border: 1.5px solid color-mix(in srgb, var(--accent) 55%, transparent);
    cursor: crosshair;
    z-index: 3;
  }
  .handle.l {
    left: -5px;
  }
  .handle.r {
    right: -5px;
  }
  .col-row:hover .handle,
  .handle:hover {
    background: var(--accent);
  }
  .canvas-hint {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 6px;
    max-width: 360px;
    text-align: center;
    color: var(--text-dim);
    pointer-events: none;
  }
  .canvas-hint p {
    margin: 0;
    font-size: var(--fs-s);
    line-height: 1.5;
  }
  .canvas-hint .ch-title {
    color: var(--text);
    font-size: var(--fs-m);
    font-weight: 500;
  }
  .canvas-bar {
    position: absolute;
    inset-inline: 10px;
    bottom: 10px;
    z-index: 4;
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 6px;
    padding: 6px 8px;
    border-radius: var(--radius-m);
    background: var(--surface);
    border: 1px solid var(--border);
  }
  .cb-warn {
    display: inline-flex;
    align-items: center;
    gap: 5px;
    font-size: var(--fs-xs);
    color: var(--warning);
  }
  .fk-chip {
    display: inline-flex;
    align-items: center;
    gap: 4px;
    height: 22px;
    padding: 0 9px;
    border-radius: 999px;
    border: 1px dashed color-mix(in srgb, var(--accent) 45%, transparent);
    background: transparent;
    color: var(--accent-text);
    font-size: var(--fs-xs);
    font-family: var(--font-mono);
    cursor: pointer;
  }
  .fk-chip:hover {
    background: var(--accent-soft);
  }
  .split {
    flex: 0 0 7px;
    display: grid;
    place-items: center;
    cursor: row-resize;
    border-top: 1px solid var(--border);
    touch-action: none;
  }
  .split:hover {
    background: color-mix(in srgb, var(--accent) 12%, transparent);
  }
  .grip {
    width: 36px;
    height: 3px;
    border-radius: 999px;
    background: var(--border-strong);
  }

  /* ── Designer ── */
  .designer {
    flex: 1;
    min-height: 0;
    display: grid;
    grid-template-columns: minmax(0, 1fr) minmax(280px, 38%);
  }
  .clauses {
    min-height: 0;
    overflow-y: auto;
    scrollbar-gutter: stable;
    padding: 8px 14px 16px;
  }
  .clauses.disabled {
    opacity: 0.55;
    pointer-events: none;
  }
  .notice {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 6px 10px;
    margin-bottom: 8px;
    border-radius: var(--radius-s);
    border: 1px solid var(--border);
    font-size: var(--fs-s);
    color: var(--text-dim);
  }
  .notice.err {
    color: var(--text);
    background: var(--danger-soft);
    border-color: color-mix(in srgb, var(--danger) 35%, transparent);
  }
  .notice.err :global(svg) {
    color: var(--danger);
  }
  .notice span {
    flex: 1;
  }
  .sec {
    padding: 8px 0 10px;
    border-bottom: 1px solid color-mix(in srgb, var(--border) 70%, transparent);
  }
  .sec:last-child {
    border-bottom: none;
  }
  .sec-head {
    display: flex;
    align-items: center;
    gap: 8px;
    min-height: 26px;
    margin-bottom: 4px;
    flex-wrap: wrap;
  }
  .sec-head h3 {
    margin: 0;
  }
  .sec-count {
    font-size: var(--fs-xs);
    color: var(--text-dim);
  }
  .distinct {
    display: inline-flex;
    align-items: center;
    gap: 5px;
    font-size: var(--fs-s);
    color: var(--text-dim);
    margin-inline-start: 6px;
  }
  .sec-hint {
    margin: 2px 0 0;
    font-size: var(--fs-s);
    color: var(--text-dim);
  }
  .sec-hint code {
    font-family: var(--font-mono);
  }
  .row {
    display: flex;
    align-items: center;
    gap: 6px;
    margin-top: 5px;
    min-width: 0;
  }
  .row .input {
    height: 26px;
    min-width: 0;
    font-size: var(--fs-s);
  }
  .ord {
    width: 16px;
    flex-shrink: 0;
    text-align: end;
    font-size: var(--fs-xs);
    color: var(--text-dim);
    font-variant-numeric: tabular-nums;
  }
  .grow-2 {
    flex: 2 1 140px;
  }
  .fn {
    flex: 0 0 132px;
  }
  .alias {
    flex: 1 1 90px;
    max-width: 160px;
  }
  .as {
    font-size: var(--fs-xs);
    color: var(--text-dim);
    font-weight: 600;
    flex-shrink: 0;
  }
  .col {
    flex: 2 1 130px;
  }
  .op {
    flex: 0 0 132px;
  }
  .val {
    flex: 2 1 110px;
  }
  .val.half {
    flex: 1 1 70px;
  }
  .val.none {
    flex: 2 1 110px;
  }
  .nulls {
    flex: 0 0 128px;
  }
  .dir {
    flex-shrink: 0;
  }
  .add-select {
    height: 24px;
    width: auto;
    font-size: var(--fs-s);
  }
  .chips {
    display: flex;
    flex-wrap: wrap;
    gap: 6px;
    margin-top: 4px;
  }
  .chips .chip {
    display: inline-flex;
    align-items: center;
    gap: 4px;
    padding-inline-end: 3px;
  }
  .chip-x {
    display: inline-grid;
    place-items: center;
    width: 16px;
    height: 16px;
    border: none;
    border-radius: 999px;
    background: transparent;
    color: var(--text-dim);
    cursor: pointer;
  }
  .chip-x:hover {
    background: var(--danger-soft);
    color: var(--danger);
  }
  .limits {
    display: flex;
    gap: 16px;
  }
  .lim {
    display: inline-flex;
    align-items: center;
    gap: 8px;
  }
  .lim .input {
    width: 96px;
    height: 26px;
  }
  /* Condition groups: an inset rule per nesting level. */
  .cgroup {
    display: flex;
    flex-direction: column;
  }
  .cgroup.nested {
    padding: 4px 0 6px 10px;
    border-inline-start: 2px solid var(--border-strong);
    flex: 1;
    min-width: 0;
  }
  .cg-head {
    display: flex;
    align-items: center;
    gap: 8px;
    margin-top: 4px;
  }
  .cg-hint {
    font-size: var(--fs-xs);
    color: var(--text-dim);
  }
  .conj > button {
    height: 20px;
    padding: 0 8px;
    font-size: var(--fs-xs);
    font-weight: 600;
  }
  .cg-item {
    display: flex;
    align-items: flex-start;
    gap: 6px;
    margin-top: 6px;
  }
  .cg-x {
    margin-top: 4px;
  }

  /* ── SQL pane ── */
  .sql-pane {
    display: flex;
    flex-direction: column;
    min-height: 0;
    min-width: 0;
    border-inline-start: 1px solid var(--border);
    background: var(--surface);
  }
  .sql-head {
    display: flex;
    align-items: center;
    gap: 8px;
    height: 34px;
    padding: 0 10px 0 14px;
    border-bottom: 1px solid var(--border);
    flex-shrink: 0;
  }
  .sql-dialect {
    font-size: var(--fs-xs);
    color: var(--text-dim);
  }
  .issues {
    list-style: none;
    margin: 0;
    padding: 6px 12px;
    display: flex;
    flex-direction: column;
    gap: 4px;
    border-bottom: 1px solid var(--border);
    flex-shrink: 0;
  }
  .issues li {
    display: flex;
    align-items: center;
    gap: 6px;
    font-size: var(--fs-s);
    color: var(--text);
  }
  .issues li :global(svg) {
    color: var(--warning);
    flex-shrink: 0;
  }
  .issues li.err :global(svg) {
    color: var(--danger);
  }
  .issues li span {
    flex: 1;
  }
  .sql {
    flex: 1;
    min-height: 0;
    margin: 0;
    padding: 12px 14px;
    overflow: auto;
    font-size: var(--fs-s);
    line-height: 1.6;
    white-space: pre-wrap;
    word-break: break-word;
    user-select: text;
    color: var(--text);
    background: var(--surface-2);
  }
  .sql :global(.kw) {
    color: var(--accent-text);
    font-weight: 600;
  }
  .sql :global(.str) {
    color: var(--success);
  }
  .sql :global(.num) {
    color: var(--info);
  }
  .sql :global(.id) {
    color: var(--text);
  }
  .sql-empty {
    color: var(--text-dim);
    font-family: var(--font-ui);
  }
  .sql-actions {
    display: flex;
    justify-content: flex-end;
    gap: 8px;
    padding: 8px 10px;
    border-top: 1px solid var(--border);
    flex-shrink: 0;
  }
  .grow {
    flex: 1;
  }
  /* A narrow designer (small window, docked pane) stacks the SQL under the
     clauses instead of squeezing both. */
  @container (max-width: 760px) {
    .designer {
      grid-template-columns: minmax(0, 1fr);
      grid-template-rows: minmax(0, 1fr) minmax(0, 40%);
    }
    .sql-pane {
      border-inline-start: none;
      border-top: 1px solid var(--border);
    }
  }
</style>
