<script lang="ts">
 import type {GamePlayer} from './types';
 import {WEAPONS} from './weapons';
 let {self,onweapon}:{self:GamePlayer;onweapon:(slot:number)=>void}=$props();
 const weapon=$derived(WEAPONS[self.weapon]);
</script>
<div class="combat-vitals"><span>Vital signs</span><div><strong>{self.hp}</strong><progress value={self.hp} max="100" aria-label="Health"></progress></div><div class="combat-shield"><span>Shield {Math.ceil(self.shield)}</span><progress value={self.shield} max="100" aria-label="Shield"></progress></div><small>{self.dashCooldown>0?`Dash ${self.dashCooldown.toFixed(1)}s`:'E · Dash ready'}</small></div>
<div class="combat-loadout"><div class="combat-ammo"><span>{self.reloadTime>0?'Reloading…':weapon.name}</span><strong>{self.ammo}<small> / {weapon.capacity}</small></strong></div><div class="combat-weapons">{#each ['rifle','scatter','rail'] as id,i}<button aria-label={`Equip ${WEAPONS[id as keyof typeof WEAPONS].name}`} aria-pressed={self.weapon===id} onclick={()=>onweapon(i+1)}><kbd>{i+1}</kbd>{WEAPONS[id as keyof typeof WEAPONS].name}</button>{/each}</div></div>
<style>
 .combat-vitals,.combat-loadout{position:absolute;inset-block-end:24px;color:var(--on-scrim);background:var(--scrim-media);border:1px solid color-mix(in srgb,var(--on-scrim) 20%,transparent);padding:14px 18px;border-radius:var(--radius-m);}.combat-vitals{inset-inline-start:20px;width:200px;display:grid;gap:8px;pointer-events:none;}.combat-vitals>span{font-size:var(--fs-s);opacity:.75;}.combat-vitals>div{display:flex;align-items:center;gap:12px;}.combat-vitals strong{font-size:var(--fs-2xl);}.combat-vitals progress{height:8px;flex:1;min-width:0;accent-color:var(--success);}.combat-vitals .combat-shield{display:grid;gap:4px;}.combat-shield span,.combat-vitals small{font-size:var(--fs-s);}.combat-shield progress{width:100%;accent-color:var(--info);}.combat-loadout{inset-inline-end:20px;display:grid;gap:10px;}.combat-ammo{display:flex;align-items:center;justify-content:space-between;gap:24px;}.combat-ammo span{font-size:var(--fs-m);}.combat-ammo strong{font-size:var(--fs-2xl);}.combat-ammo small{font-size:var(--fs-m);font-weight:400;opacity:.6;}.combat-weapons{display:flex;gap:6px;}.combat-weapons button{border:1px solid color-mix(in srgb,var(--on-scrim) 25%,transparent);background:transparent;color:var(--on-scrim);padding:8px 10px;border-radius:var(--radius-s);cursor:pointer;font-size:var(--fs-s);}.combat-weapons button[aria-pressed=true]{border-color:var(--accent-solid);background:var(--accent-soft);}.combat-weapons kbd{margin-inline-end:8px;opacity:.6;font-size:var(--fs-s);}
 @media(max-width:640px){.combat-vitals,.combat-loadout{inset-block-end:8px;padding:8px;}.combat-vitals{inset-inline-start:8px;width:115px;gap:4px;}.combat-vitals strong{font-size:var(--fs-xl);}.combat-vitals>span{display:none;}.combat-loadout{inset-inline-end:8px;gap:8px;max-width:calc(100% - 140px);}.combat-ammo{gap:12px;}.combat-ammo strong{font-size:var(--fs-xl);}.combat-weapons{gap:4px;}.combat-weapons button{padding:6px;}.combat-weapons kbd{display:none;}}
</style>
